version: '3.3'

services:
  webapp:
    container_name: memory
    build:
     context: .
     dockerfile: Dockerfile
    volumes:
      - ./conf:/etc/nginx
    ports:
      - "80:80"
      - "443:443"